version: '3'

services:

  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    restart: always
    ports:
      - 443:80
    volumes:
      - .:/var/www/app

  smtp:
    build: ./docker/mms
    restart: always
    expose:
      - 25
    volumes:
      - .:/var/www/app
