version: '3'

services:
  mms:
    restart: always
    image: 808964640426.dkr.ecr.us-east-1.amazonaws.com/kontxt-smtp-emulator:1
    volumes:
      - ./server.js:/usr/src/app/server.js
    ports:
      - 25:10025
    #logging:
     # driver: none
    command: npm start
    networks:
      - obanmicro_default

networks:
  obanmicro_default:
    external: true