version: '3'

services:
  mms:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 25:10025
    command: npm start

    networks:
      - obanmicro_default


networks:
  obanmicro_default:
    external: true