version: '3'

services:
  mms:
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 443:10025
    logging:
      driver: none
    command: npm start
    networks:
      - obanmicro_default


networks:
  obanmicro_default:
    external: true